### ISSUE TITLE
Add AmphibiaWeb species account URL

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/SpeciesLookup#2]
For each species that is returned from a lookup, add AW link, which is formed for each species:

https://amphibiaweb.org/cgi/amphib_query?where-genus=Microhyla&where-species=fissipes

**Comment by Chenyu-Shi** [comment]
resolved in the json version of the api. Try specieslookup.berkeley.edu/search_json/-122.264776,37.870871
