### ISSUE TITLE
Add family name to json output

### ISSUE THREAD

**Issue by jdeck88** [AmphibiaWeb/SpeciesLookup#5]
Insert family name into json response

**Comment by mkoo** [comment]
If you implement a lookup function then this is where Amphibiaweb lists the daily taxonomy:

https://amphibiaweb.org/amphib_names.txt

**Comment by jdeck88** [comment]
also great to add class and order...

**Comment by Chenyu-Shi** [comment]
Family name is supported in the json version of this. Will work on adding class and order. Try specieslookup.berkeley.edu/search/-122.264776,37.870871

**Comment by Chenyu-Shi** [comment]
Class and order are added to the json response
