### ISSUE TITLE
Create map interface for query

### ISSUE THREAD

**Issue by jdeck88** [AmphibiaWeb/SpeciesLookup#7]
On the home/landing page specieslookup.berkeley.edu we want to open a full page map in leaflet, zoom into current location and then drop pin to get query results... this would replace the current page.

**Comment by mkoo** [comment]
Can we allow a feature search option? Say you want ot check out Bombay,
India and are too lazy to pan....

Can we create a few new pages with links on the front page? Specifically an
About page to throw current home page contents on. I can create a new issue
actually...

**Comment by jdeck88** [comment]
done...
