### ISSUE TITLE
resize or move info box a couple of pixels north

### ISSUE THREAD

**Issue by mkoo** [AmphibiaWeb/SpeciesLookup#9]
the info box is cutoff when flush to the bottom left of screen. See:

<img width="496" alt="Screen Shot 2019-07-23 at 9 57 00 PM" src="https://user-images.githubusercontent.com/2523089/61764567-dd3d6a00-ad96-11e9-8a75-71b5443e5543.png">
and blocked by GM credits:
<img width="535" alt="Screen Shot 2019-07-23 at 10 06 03 PM" src="https://user-images.githubusercontent.com/2523089/61764575-e3cbe180-ad96-11e9-8937-136b70806be3.png">

Maybe also add a slidertray option

**Comment by mkoo** [comment]
A little shortening of text cant hurt either:
```
SpeciesLookup is a species query service returning a list of amphibian species whose ranges intersect at a location. Original code was developed by Chenyu Shi, Undergraduate, Museum of Vertebrate Zoology, UC Berkeley.

Query the service directly by replacing the coordinates below (without the brackets):
https://specieslookup.berkeley.edu/search/[longitude,latitude]
Github link
```

**Comment by jdeck88** [comment]
fixed.
